version: '3.8'

services:
  backend:
    build: ./backend
    container_name: devflow_api
    ports:
      - "5113:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/devflow
      - JWT_SECRET=devflowsecret
      - NODE_ENV=development
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: devflow_ui
    ports:
      - "3113:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mongodb:
    image: mongo:4.4
    container_name: devflow_db
    ports:
      - "27113:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
